name: Blue-Green Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Deployment Package
      run: |
       cd app
       zip -r deploy.zip . -x "*.git*" "node_modules/*"

    - name: Deploy to Green Environment
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: blue-green-demo  
        environment_name: bg-demo-green    
        version_label: "ver-${{ github.sha }}"
        region: ap-south-1
        deployment_package: deploy.zip

    - name: Swap Blue and Green
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1
      run: |
        echo "Deploy successful. Swapping CNAMES..."
        aws elasticbeanstalk swap-environment-cnames \
          --source-environment-name bg-demo-blue \
          --destination-environment-name bg-demo-green
        echo "Swap complete! bg-demo-green is now LIVE."